value="[[[],[[""CROSS_A"",""CROSS_A"",""ACRE_PRC148"",[],true],[""CROSS_B"",""CROSS_B"",""ACRE_PRC148"",[],true],[""CROSS_C"",""CROSS_C"",""ACRE_PRC148"",[],true],[""CSF_C2"",""CSF_C2"",""ACRE_PRC148"",[],true],[""JTF2_A"",""JTF2_A"",""ACRE_PRC148"",[],true],[""JTF2_B"",""JTF2_B"",""ACRE_PRC148"",[],true],[""CSOR_A"",""CSOR_A"",""ACRE_PRC148"",[],true],[""CSOR_B"",""CSOR_B"",""ACRE_PRC148"",[],true],[""CSOR_C"",""CSOR_C"",""ACRE_PRC148"",[],true],[""SOCOM"",""SOCOM"",""ACRE_PRC148"",[],true],[""DELTA_A"",""DELTA_A"",""ACRE_PRC148"",[],true],[""DELTA_B"",""DELTA_B"",""ACRE_PRC148"",[],true],[""DELTA_C"",""DELTA_C"",""ACRE_PRC148"",[],true],[""75RBTN_A"",""75RBTN_A"",""ACRE_PRC148"",[],true],[""75RBTN_B"",""75RBTN_B"",""ACRE_PRC148"",[],true],[""HQ_1"",""HQ_1"",""ACRE_PRC152"",[],true],[""HQ_2"",""HQ_2"",""ACRE_PRC152"",[],true],[""HQ_3"",""HQ_3"",""ACRE_PRC152"",[],true],[""CROSS_1"",""CROSS_1"",""ACRE_PRC152"",[],true],[""CROSS_2"",""CROSS_2"",""ACRE_PRC152"",[],true],[""CROSS_3"",""CROSS_3"",""ACRE_PRC152"",[],true],[""CSF_C2"",""CSF_C2_NET"",""ACRE_PRC152"",[],true],[""JTF2"",""JTF2"",""ACRE_PRC152"",[],true],[""CSOR"",""CSOR"",""ACRE_PRC152"",[],true],[""SOCOM_C2"",""SOCOM_C2"",""ACRE_PRC152"",[],true],[""DELTA"",""DELTA"",""ACRE_PRC152"",[],true],[""75RBNT"",""75RBNT"",""ACRE_PRC152"",[],true],[""TFD_C2"",""TFD_C2"",""ACRE_PRC117F"",[],true],[""AIR_C2_NET"",""AIR_C2_NET"",""ACRE_PRC117F"",[],true],[""AIR2GND_NET1"",""AIR2GND_NET1"",""ACRE_PRC117F"",[],true],[""AIR2GND_NET2"",""AIR2GND_NET2"",""ACRE_PRC117F"",[],true],[""FLIGHT_NET1"",""FLIGHT_NET1"",""ACRE_PRC117F"",[],true],[""FLIGHT_NET2"",""FLIGHT_NET2"",""ACRE_PRC117F"",[],true],[""FLIGHT_NET3"",""FLIGHT_NET3"",""ACRE_PRC117F"",[],true],[""CAS_NET1"",""CAS_NET1"",""ACRE_PRC117F"",[],true],[""CAS_NET2"",""CAS_NET2"",""ACRE_PRC117F"",[],true],[""CROSS_NET_X"",""CROSS_NET_X"",""ACRE_PRC117F"",[],true],[""CROSS_NET_Y"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true],[""CROSS_NET_Z"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true]]],[[],[[""CSF_C2"",""CSF_C2"",""ACRE_PRC148"",[],true],[""JTF2_A"",""JTF2_A"",""ACRE_PRC148"",[],true],[""JTF2_B"",""JTF2_B"",""ACRE_PRC148"",[],true],[""CSOR_A"",""CSOR_A"",""ACRE_PRC148"",[],true],[""CSOR_B"",""CSOR_B"",""ACRE_PRC148"",[],true],[""CSOR_C"",""CSOR_C"",""ACRE_PRC148"",[],true],[""CROSS_A"",""CROSS_A"",""ACRE_PRC148"",[],true],[""CROSS_B"",""CROSS_B"",""ACRE_PRC148"",[],true],[""CROSS_C"",""CROSS_C"",""ACRE_PRC148"",[],true],[""SOCOM"",""SOCOM"",""ACRE_PRC148"",[],true],[""DELTA_A"",""DELTA_A"",""ACRE_PRC148"",[],true],[""DELTA_B"",""DELTA_B"",""ACRE_PRC148"",[],true],[""DELTA_C"",""DELTA_C"",""ACRE_PRC148"",[],true],[""75RBTN_A"",""75RBTN_A"",""ACRE_PRC148"",[],true],[""75RBTN_B"",""75RBTN_B"",""ACRE_PRC148"",[],true],[""CSF_C2"",""CSF_C2_NET"",""ACRE_PRC152"",[],true],[""JTF2"",""JTF2"",""ACRE_PRC152"",[],true],[""CSOR"",""CSOR"",""ACRE_PRC152"",[],true],[""CROSS_1"",""CROSS_1"",""ACRE_PRC152"",[],true],[""CROSS_2"",""CROSS_2"",""ACRE_PRC152"",[],true],[""CROSS_3"",""CROSS_3"",""ACRE_PRC152"",[],true],[""SOCOM_C2"",""SOCOM_C2"",""ACRE_PRC152"",[],true],[""DELTA"",""DELTA"",""ACRE_PRC152"",[],true],[""75RBNT"",""75RBNT"",""ACRE_PRC152"",[],true],[""TFD_C2"",""TFD_C2"",""ACRE_PRC117F"",[],true],[""AIR_C2_NET"",""AIR_C2_NET"",""ACRE_PRC117F"",[],true],[""AIR2GND_NET1"",""AIR2GND_NET1"",""ACRE_PRC117F"",[],true],[""AIR2GND_NET2"",""AIR2GND_NET2"",""ACRE_PRC117F"",[],true],[""FLIGHT_NET1"",""FLIGHT_NET1"",""ACRE_PRC117F"",[],true],[""FLIGHT_NET2"",""FLIGHT_NET2"",""ACRE_PRC117F"",[],true],[""FLIGHT_NET3"",""FLIGHT_NET3"",""ACRE_PRC117F"",[],true],[""CAS_NET1"",""CAS_NET1"",""ACRE_PRC117F"",[],true],[""CAS_NET2"",""CAS_NET2"",""ACRE_PRC117F"",[],true],[""CROSS_NET_X"",""CROSS_NET_X"",""ACRE_PRC117F"",[],true],[""CROSS_NET_Y"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true],[""CROSS_NET_Z"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true]]],[[],[[""SOCOM"",""SOCOM"",""ACRE_PRC148"",[],true],[""DELTA_A"",""DELTA_A"",""ACRE_PRC148"",[],true],[""DELTA_B"",""DELTA_B"",""ACRE_PRC148"",[],true],[""DELTA_C"",""DELTA_C"",""ACRE_PRC148"",[],true],[""75RBTN_A"",""75RBTN_A"",""ACRE_PRC148"",[],true],[""75RBTN_B"",""75RBTN_B"",""ACRE_PRC148"",[],true],[""CROSS_A"",""CROSS_A"",""ACRE_PRC148"",[],true],[""CROSS_B"",""CROSS_B"",""ACRE_PRC148"",[],true],[""CROSS_C"",""CROSS_C"",""ACRE_PRC148"",[],true],[""CSF_C2"",""CSF_C2"",""ACRE_PRC148"",[],true],[""JTF2_A"",""JTF2_A"",""ACRE_PRC148"",[],true],[""JTF2_B"",""JTF2_B"",""ACRE_PRC148"",[],true],[""CSOR_A"",""CSOR_A"",""ACRE_PRC148"",[],true],[""CSOR_B"",""CSOR_B"",""ACRE_PRC148"",[],true],[""CSOR_C"",""CSOR_C"",""ACRE_PRC148"",[],true],[""SOCOM_C2"",""SOCOM_C2"",""ACRE_PRC152"",[],true],[""DELTA"",""DELTA"",""ACRE_PRC152"",[],true],[""75RBNT"",""75RBNT"",""ACRE_PRC152"",[],true],[""CROSS_1"",""CROSS_1"",""ACRE_PRC152"",[],true],[""CROSS_2"",""CROSS_2"",""ACRE_PRC152"",[],true],[""CROSS_3"",""CROSS_3"",""ACRE_PRC152"",[],true],[""CSF_C2"",""CSF_C2_NET"",""ACRE_PRC152"",[],true],[""JTF2"",""JTF2"",""ACRE_PRC152"",[],true],[""CSOR"",""CSOR"",""ACRE_PRC152"",[],true],[""TFD_C2"",""TFD_C2"",""ACRE_PRC117F"",[],true],[""AIR_C2_NET"",""AIR_C2_NET"",""ACRE_PRC117F"",[],true],[""AIR2GND_NET1"",""AIR2GND_NET1"",""ACRE_PRC117F"",[],true],[""AIR2GND_NET2"",""AIR2GND_NET2"",""ACRE_PRC117F"",[],true],[""FLIGHT_NET1"",""FLIGHT_NET1"",""ACRE_PRC117F"",[],true],[""FLIGHT_NET2"",""FLIGHT_NET2"",""ACRE_PRC117F"",[],true],[""FLIGHT_NET3"",""FLIGHT_NET3"",""ACRE_PRC117F"",[],true],[""CAS_NET1"",""CAS_NET1"",""ACRE_PRC117F"",[],true],[""CAS_NET2"",""CAS_NET2"",""ACRE_PRC117F"",[],true],[""CROSS_NET_X"",""CROSS_NET_X"",""ACRE_PRC117F"",[],true],[""CROSS_NET_Y"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true],[""CROSS_NET_Z"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true]]],[[],[[""CROSS_A"",""CROSS_A"",""ACRE_PRC148"",[],true],[""CROSS_B"",""CROSS_B"",""ACRE_PRC148"",[],true],[""CROSS_C"",""CROSS_C"",""ACRE_PRC148"",[],true],[""CSF_C2"",""CSF_C2"",""ACRE_PRC148"",[],true],[""JTF2_A"",""JTF2_A"",""ACRE_PRC148"",[],true],[""JTF2_B"",""JTF2_B"",""ACRE_PRC148"",[],true],[""CSOR_A"",""CSOR_A"",""ACRE_PRC148"",[],true],[""CSOR_B"",""CSOR_B"",""ACRE_PRC148"",[],true],[""CSOR_C"",""CSOR_C"",""ACRE_PRC148"",[],true],[""SOCOM"",""SOCOM"",""ACRE_PRC148"",[],true],[""DELTA_A"",""DELTA_A"",""ACRE_PRC148"",[],true],[""DELTA_B"",""DELTA_B"",""ACRE_PRC148"",[],true],[""DELTA_C"",""DELTA_C"",""ACRE_PRC148"",[],true],[""75RBTN_A"",""75RBTN_A"",""ACRE_PRC148"",[],true],[""75RBTN_B"",""75RBTN_B"",""ACRE_PRC148"",[],true],[""JSOW"",""JSOW"",""ACRE_PRC152"",[],true],[""CREW_1"",""CREW_1"",""ACRE_PRC152"",[],true],[""CREW_2"",""CREW_2"",""ACRE_PRC152"",[],true],[""CREW_3"",""CREW_3"",""ACRE_PRC152"",[],true],[""CREW_4"",""CREW_4"",""ACRE_PRC152"",[],true],[""CROSS_1"",""CROSS_1"",""ACRE_PRC152"",[],true],[""CROSS_2"",""CROSS_2"",""ACRE_PRC152"",[],true],[""CROSS_3"",""CROSS_3"",""ACRE_PRC152"",[],true],[""TFD_C2"",""TFD_C2"",""ACRE_PRC117F"",[],true],[""AIR_C2_NET"",""AIR_C2_NET"",""ACRE_PRC117F"",[],true],[""AIR2GND_NET1"",""AIR2GND_NET1"",""ACRE_PRC117F"",[],true],[""AIR2GND_NET2"",""AIR2GND_NET2"",""ACRE_PRC117F"",[],true],[""FLIGHT_NET1"",""FLIGHT_NET1"",""ACRE_PRC117F"",[],true],[""FLIGHT_NET2"",""FLIGHT_NET2"",""ACRE_PRC117F"",[],true],[""FLIGHT_NET3"",""FLIGHT_NET3"",""ACRE_PRC117F"",[],true],[""CAS_NET1"",""CAS_NET1"",""ACRE_PRC117F"",[],true],[""CAS_NET2"",""CAS_NET2"",""ACRE_PRC117F"",[],true],[""CROSS_NET_X"",""CROSS_NET_X"",""ACRE_PRC117F"",[],true],[""CROSS_NET_Y"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true],[""CROSS_NET_Z"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true]]],[[],[[""TRAINING"",""TRAINING"",""ACRE_PRC148"",[],true],[""CANSOFCOM"",""CANSOFCOM"",""ACRE_PRC148"",[],true],[""USASOC"",""USASOC"",""ACRE_PRC148"",[],true],[""CROSS_A"",""CROSS_A"",""ACRE_PRC148"",[],true],[""CROSS_B"",""CROSS_B"",""ACRE_PRC148"",[],true],[""CROSS_C"",""CROSS_C"",""ACRE_PRC148"",[],true],[""TRAINING_1"",""TRAINING_1"",""ACRE_PRC152"",[],true],[""TRAINING_2"",""TRAINING_2"",""ACRE_PRC152"",[],true],[""CROSS_1"",""CROSS_1"",""ACRE_PRC152"",[],true],[""CROSS_2"",""CROSS_2"",""ACRE_PRC152"",[],true],[""CROSS_3"",""CROSS_3"",""ACRE_PRC152"",[],true],[""TFD_C2"",""TFD_C2"",""ACRE_PRC117F"",[],true],[""AIR_C2_NET"",""AIR_C2_NET"",""ACRE_PRC117F"",[],true],[""AIR2GND_NET1"",""AIR2GND_NET1"",""ACRE_PRC117F"",[],true],[""AIR2GND_NET2"",""AIR2GND_NET2"",""ACRE_PRC117F"",[],true],[""FLIGHT_NET1"",""FLIGHT_NET1"",""ACRE_PRC117F"",[],true],[""FLIGHT_NET2"",""FLIGHT_NET2"",""ACRE_PRC117F"",[],true],[""FLIGHT_NET3"",""FLIGHT_NET3"",""ACRE_PRC117F"",[],true],[""CAS_NET1"",""CAS_NET1"",""ACRE_PRC117F"",[],true],[""CAS_NET2"",""CAS_NET2"",""ACRE_PRC117F"",[],true],[""CROSS_NET_X"",""CROSS_NET_X"",""ACRE_PRC117F"",[],true],[""CROSS_NET_Y"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true],[""CROSS_NET_Z"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true]]]]";


//easy to read ish for me work part
value="
[
    [
        [],
        [
            [""CROSS_A"", ""CROSS_A"", ""ACRE_PRC148"", [], true],
            [""CROSS_B"", ""CROSS_B"", ""ACRE_PRC148"", [], true],
            [""CROSS_C"", ""CROSS_C"", ""ACRE_PRC148"", [], true],
            [""CSF_C2"", ""CSF_C2"", ""ACRE_PRC148"", [], true],
            [""JTF2_A"", ""JTF2_A"", ""ACRE_PRC148"", [], true],
            [""JTF2_B"", ""JTF2_B"", ""ACRE_PRC148"", [], true],
            [""CSOR_A"", ""CSOR_A"", ""ACRE_PRC148"", [], true],
            [""CSOR_B"", ""CSOR_B"", ""ACRE_PRC148"", [], true],
            [""CSOR_C"", ""CSOR_C"", ""ACRE_PRC148"", [], true],
            [""SOCOM"", ""SOCOM"", ""ACRE_PRC148"", [], true],
            [""DELTA_A"", ""DELTA_A"", ""ACRE_PRC148"", [], true],
            [""DELTA_B"", ""DELTA_B"", ""ACRE_PRC148"", [], true],
            [""DELTA_C"", ""DELTA_C"", ""ACRE_PRC148"", [], true],
            [""75RBTN_A"", ""75RBTN_A"", ""ACRE_PRC148"", [], true],
            [""75RBTN_B"", ""75RBTN_B"", ""ACRE_PRC148"", [], true],
            [""HQ_1"", ""HQ_1"", ""ACRE_PRC152"", [], true],
            [""HQ_2"", ""HQ_2"", ""ACRE_PRC152"", [], true],
            [""HQ_3"", ""HQ_3"", ""ACRE_PRC152"", [], true],
            [""CROSS_1"", ""CROSS_1"", ""ACRE_PRC152"", [], true],
            [""CROSS_2"", ""CROSS_2"", ""ACRE_PRC152"", [], true],
            [""CROSS_3"", ""CROSS_3"", ""ACRE_PRC152"", [], true],
            [""CSF_C2"", ""CSF_C2_NET"", ""ACRE_PRC152"", [], true],
            [""JTF2"", ""JTF2"", ""ACRE_PRC152"", [], true],
            [""CSOR"", ""CSOR"", ""ACRE_PRC152"", [], true],
            [""SOCOM_C2"", ""SOCOM_C2"", ""ACRE_PRC152"", [], true],
            [""DELTA"", ""DELTA"", ""ACRE_PRC152"", [], true],
            [""75RBNT"", ""75RBNT"", ""ACRE_PRC152"", [], true],
            [""TFD_C2"",""TFD_C2"",""ACRE_PRC117F"",[],true],
            [""AIR_C2_NET"",""AIR_C2_NET"",""ACRE_PRC117F"",[],true],
            [""AIR2GND_NET1"",""AIR2GND_NET1"",""ACRE_PRC117F"",[],true],
            [""AIR2GND_NET2"",""AIR2GND_NET2"",""ACRE_PRC117F"",[],true],
            [""FLIGHT_NET1"",""FLIGHT_NET1"",""ACRE_PRC117F"",[],true],
            [""FLIGHT_NET2"",""FLIGHT_NET2"",""ACRE_PRC117F"",[],true],
            [""FLIGHT_NET3"",""FLIGHT_NET3"",""ACRE_PRC117F"",[],true],
            [""CAS_NET1"",""CAS_NET1"",""ACRE_PRC117F"",[],true],
            [""CAS_NET2"",""CAS_NET2"",""ACRE_PRC117F"",[],true],
            [""CROSS_NET_X"",""CROSS_NET_X"",""ACRE_PRC117F"",[],true],
            [""CROSS_NET_Y"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true],
            [""CROSS_NET_Z"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true]
        ]
    ],
    [
        [],
        [
            [""CSF_C2"", ""CSF_C2"", ""ACRE_PRC148"", [], true],
            [""JTF2_A"", ""JTF2_A"", ""ACRE_PRC148"", [], true],
            [""JTF2_B"", ""JTF2_B"", ""ACRE_PRC148"", [], true],
            [""CSOR_A"", ""CSOR_A"", ""ACRE_PRC148"", [], true],
            [""CSOR_B"", ""CSOR_B"", ""ACRE_PRC148"", [], true],
            [""CSOR_C"", ""CSOR_C"", ""ACRE_PRC148"", [], true],
            [""CROSS_A"", ""CROSS_A"", ""ACRE_PRC148"", [], true],
            [""CROSS_B"", ""CROSS_B"", ""ACRE_PRC148"", [], true],
            [""CROSS_C"", ""CROSS_C"", ""ACRE_PRC148"", [], true],
            [""SOCOM"", ""SOCOM"", ""ACRE_PRC148"", [], true],
            [""DELTA_A"", ""DELTA_A"", ""ACRE_PRC148"", [], true],
            [""DELTA_B"", ""DELTA_B"", ""ACRE_PRC148"", [], true],
            [""DELTA_C"", ""DELTA_C"", ""ACRE_PRC148"", [], true],
            [""75RBTN_A"", ""75RBTN_A"", ""ACRE_PRC148"", [], true],
            [""75RBTN_B"", ""75RBTN_B"", ""ACRE_PRC148"", [], true],
            [""CSF_C2"", ""CSF_C2_NET"", ""ACRE_PRC152"", [], true],
            [""JTF2"", ""JTF2"", ""ACRE_PRC152"", [], true],
            [""CSOR"", ""CSOR"", ""ACRE_PRC152"", [], true],
            [""CROSS_1"", ""CROSS_1"", ""ACRE_PRC152"", [], true],
            [""CROSS_2"", ""CROSS_2"", ""ACRE_PRC152"", [], true],
            [""CROSS_3"", ""CROSS_3"", ""ACRE_PRC152"", [], true],
            [""SOCOM_C2"", ""SOCOM_C2"", ""ACRE_PRC152"", [], true],
            [""DELTA"", ""DELTA"", ""ACRE_PRC152"", [], true],
            [""75RBNT"", ""75RBNT"", ""ACRE_PRC152"", [], true],
            [""TFD_C2"",""TFD_C2"",""ACRE_PRC117F"",[],true],
            [""AIR_C2_NET"",""AIR_C2_NET"",""ACRE_PRC117F"",[],true],
            [""AIR2GND_NET1"",""AIR2GND_NET1"",""ACRE_PRC117F"",[],true],
            [""AIR2GND_NET2"",""AIR2GND_NET2"",""ACRE_PRC117F"",[],true],
            [""FLIGHT_NET1"",""FLIGHT_NET1"",""ACRE_PRC117F"",[],true],
            [""FLIGHT_NET2"",""FLIGHT_NET2"",""ACRE_PRC117F"",[],true],
            [""FLIGHT_NET3"",""FLIGHT_NET3"",""ACRE_PRC117F"",[],true],
            [""CAS_NET1"",""CAS_NET1"",""ACRE_PRC117F"",[],true],
            [""CAS_NET2"",""CAS_NET2"",""ACRE_PRC117F"",[],true],
            [""CROSS_NET_X"",""CROSS_NET_X"",""ACRE_PRC117F"",[],true],
            [""CROSS_NET_Y"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true],
            [""CROSS_NET_Z"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true]
        ]
    ],
    [
        [],
        [
            [""SOCOM"", ""SOCOM"", ""ACRE_PRC148"", [], true],
            [""DELTA_A"", ""DELTA_A"", ""ACRE_PRC148"", [], true],
            [""DELTA_B"", ""DELTA_B"", ""ACRE_PRC148"", [], true],
            [""DELTA_C"", ""DELTA_C"", ""ACRE_PRC148"", [], true],
            [""75RBTN_A"", ""75RBTN_A"", ""ACRE_PRC148"", [], true],
            [""75RBTN_B"", ""75RBTN_B"", ""ACRE_PRC148"", [], true],
            [""CROSS_A"", ""CROSS_A"", ""ACRE_PRC148"", [], true],
            [""CROSS_B"", ""CROSS_B"", ""ACRE_PRC148"", [], true],
            [""CROSS_C"", ""CROSS_C"", ""ACRE_PRC148"", [], true],
            [""CSF_C2"", ""CSF_C2"", ""ACRE_PRC148"", [], true],
            [""JTF2_A"", ""JTF2_A"", ""ACRE_PRC148"", [], true],
            [""JTF2_B"", ""JTF2_B"", ""ACRE_PRC148"", [], true],
            [""CSOR_A"", ""CSOR_A"", ""ACRE_PRC148"", [], true],
            [""CSOR_B"", ""CSOR_B"", ""ACRE_PRC148"", [], true],
            [""CSOR_C"", ""CSOR_C"", ""ACRE_PRC148"", [], true],
            [""SOCOM_C2"", ""SOCOM_C2"", ""ACRE_PRC152"", [], true],
            [""DELTA"", ""DELTA"", ""ACRE_PRC152"", [], true],
            [""75RBNT"", ""75RBNT"", ""ACRE_PRC152"", [], true],
            [""CROSS_1"", ""CROSS_1"", ""ACRE_PRC152"", [], true],
            [""CROSS_2"", ""CROSS_2"", ""ACRE_PRC152"", [], true],
            [""CROSS_3"", ""CROSS_3"", ""ACRE_PRC152"", [], true],
            [""CSF_C2"", ""CSF_C2_NET"", ""ACRE_PRC152"", [], true],
            [""JTF2"", ""JTF2"", ""ACRE_PRC152"", [], true],
            [""CSOR"", ""CSOR"", ""ACRE_PRC152"", [], true],
            [""TFD_C2"",""TFD_C2"",""ACRE_PRC117F"",[],true],
            [""AIR_C2_NET"",""AIR_C2_NET"",""ACRE_PRC117F"",[],true],
            [""AIR2GND_NET1"",""AIR2GND_NET1"",""ACRE_PRC117F"",[],true],
            [""AIR2GND_NET2"",""AIR2GND_NET2"",""ACRE_PRC117F"",[],true],
            [""FLIGHT_NET1"",""FLIGHT_NET1"",""ACRE_PRC117F"",[],true],
            [""FLIGHT_NET2"",""FLIGHT_NET2"",""ACRE_PRC117F"",[],true],
            [""FLIGHT_NET3"",""FLIGHT_NET3"",""ACRE_PRC117F"",[],true],
            [""CAS_NET1"",""CAS_NET1"",""ACRE_PRC117F"",[],true],
            [""CAS_NET2"",""CAS_NET2"",""ACRE_PRC117F"",[],true],
            [""CROSS_NET_X"",""CROSS_NET_X"",""ACRE_PRC117F"",[],true],
            [""CROSS_NET_Y"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true],
            [""CROSS_NET_Z"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true]
        ]
    ],
    [
        [],
        [
            [""CROSS_A"", ""CROSS_A"", ""ACRE_PRC148"", [], true],
            [""CROSS_B"", ""CROSS_B"", ""ACRE_PRC148"", [], true],
            [""CROSS_C"", ""CROSS_C"", ""ACRE_PRC148"", [], true],
            [""CSF_C2"", ""CSF_C2"", ""ACRE_PRC148"", [], true],
            [""JTF2_A"", ""JTF2_A"", ""ACRE_PRC148"", [], true],
            [""JTF2_B"", ""JTF2_B"", ""ACRE_PRC148"", [], true],
            [""CSOR_A"", ""CSOR_A"", ""ACRE_PRC148"", [], true],
            [""CSOR_B"", ""CSOR_B"", ""ACRE_PRC148"", [], true],
            [""CSOR_C"", ""CSOR_C"", ""ACRE_PRC148"", [], true],
            [""SOCOM"", ""SOCOM"", ""ACRE_PRC148"", [], true],
            [""DELTA_A"", ""DELTA_A"", ""ACRE_PRC148"", [], true],
            [""DELTA_B"", ""DELTA_B"", ""ACRE_PRC148"", [], true],
            [""DELTA_C"", ""DELTA_C"", ""ACRE_PRC148"", [], true],
            [""75RBTN_A"", ""75RBTN_A"", ""ACRE_PRC148"", [], true],
            [""75RBTN_B"", ""75RBTN_B"", ""ACRE_PRC148"", [], true],
            [""JSOW"", ""JSOW"", ""ACRE_PRC152"", [], true],
            [""CREW_1"", ""CREW_1"", ""ACRE_PRC152"", [], true],
            [""CREW_2"", ""CREW_2"", ""ACRE_PRC152"", [], true],
            [""CREW_3"", ""CREW_4"", ""ACRE_PRC152"", [], true],
            [""CREW_4"", ""CREW_4"", ""ACRE_PRC152"", [], true],
            [""CROSS_1"", ""CROSS_1"", ""ACRE_PRC152"", [], true],
            [""CROSS_2"", ""CROSS_2"", ""ACRE_PRC152"", [], true],
            [""CROSS_3"", ""CROSS_3"", ""ACRE_PRC152"", [], true],
            [""TFD_C2"",""TFD_C2"",""ACRE_PRC117F"",[],true],
            [""AIR_C2_NET"",""AIR_C2_NET"",""ACRE_PRC117F"",[],true],
            [""AIR2GND_NET1"",""AIR2GND_NET1"",""ACRE_PRC117F"",[],true],
            [""AIR2GND_NET2"",""AIR2GND_NET2"",""ACRE_PRC117F"",[],true],
            [""FLIGHT_NET1"",""FLIGHT_NET1"",""ACRE_PRC117F"",[],true],
            [""FLIGHT_NET2"",""FLIGHT_NET2"",""ACRE_PRC117F"",[],true],
            [""FLIGHT_NET3"",""FLIGHT_NET3"",""ACRE_PRC117F"",[],true],
            [""CAS_NET1"",""CAS_NET1"",""ACRE_PRC117F"",[],true],
            [""CAS_NET2"",""CAS_NET2"",""ACRE_PRC117F"",[],true],
            [""CROSS_NET_X"",""CROSS_NET_X"",""ACRE_PRC117F"",[],true],
            [""CROSS_NET_Y"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true],
            [""CROSS_NET_Z"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true]
        ]
    ],
    [
        [],
        [
            [""TRAINING"", ""TRAINING"", ""ACRE_PRC148"", [], true],
            [""CANSOFCOM"", ""CANSOFCOM"", ""ACRE_PRC148"", [], true],
            [""USASOC"", ""USASOC"", ""ACRE_PRC148"", [], true],
            [""CROSS_A"", ""CROSS_A"", ""ACRE_PRC148"", [], true],
            [""CROSS_B"", ""CROSS_B"", ""ACRE_PRC148"", [], true],
            [""CROSS_C"", ""CROSS_C"", ""ACRE_PRC148"", [], true],
            [""TRAINING_1"", ""TRAINING_1"", ""ACRE_PRC152"", [], true],
            [""TRAINING_2"", ""TRAINING_2"", ""ACRE_PRC152"", [], true],
            [""CROSS_1"", ""CROSS_1"", ""ACRE_PRC152"", [], true],
            [""CROSS_2"", ""CROSS_2"", ""ACRE_PRC152"", [], true],
            [""CROSS_3"", ""CROSS_3"", ""ACRE_PRC152"", [], true],
            [""TFD_C2"",""TFD_C2"",""ACRE_PRC117F"",[],true],
            [""AIR_C2_NET"",""AIR_C2_NET"",""ACRE_PRC117F"",[],true],
            [""AIR2GND_NET1"",""AIR2GND_NET1"",""ACRE_PRC117F"",[],true],
            [""AIR2GND_NET2"",""AIR2GND_NET2"",""ACRE_PRC117F"",[],true],
            [""FLIGHT_NET1"",""FLIGHT_NET1"",""ACRE_PRC117F"",[],true],
            [""FLIGHT_NET2"",""FLIGHT_NET2"",""ACRE_PRC117F"",[],true],
            [""FLIGHT_NET3"",""FLIGHT_NET3"",""ACRE_PRC117F"",[],true],
            [""CAS_NET1"",""CAS_NET1"",""ACRE_PRC117F"",[],true],
            [""CAS_NET2"",""CAS_NET2"",""ACRE_PRC117F"",[],true],
            [""CROSS_NET_X"",""CROSS_NET_X"",""ACRE_PRC117F"",[],true],
            [""CROSS_NET_Y"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true],
            [""CROSS_NET_Z"",""CROSS_NET_Y"",""ACRE_PRC117F"",[],true]
        ]
    ]
]";



